name: dog_health
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Dependencies firebase
  firebase_database: ^10.5.1
  cloud_firestore: ^4.15.9
  shared_preferences: ^2.0.8
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  firebase_storage: ^11.2.4
  google_sign_in: ^6.2.1
  #Others dependencies
  pdf: ^3.6.0
  fl_chart: ^0.67.0
  google_fonts:
  curved_navigation_bar: ^1.0.3
  hidden_drawer_menu: ^3.0.1
  lottie: ^3.1.0
  url_launcher: ^6.2.6
  flutter_document_picker: ^5.0.0

dev_dependencies:
  change_app_package_name: ^1.1.0
  
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/